import type { Metadata } from "next";
import { Roboto,  Roboto_Mono } from "next/font/google";
import "../globals.css";

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoMono.className + " bg-black-lite overflow-hidden flex justify-center" } >
        {children}
      </body>
    </html>
  );
}
